export default{
  ADD_SEGMENT_TO_ROUTE:"ADD_SEGMENT_TO_ROUTE",
  GET_ROUTES:"GET_ROUTES",
  ADD_INDEXES_TO_MTMRECORD:"ADD_INDEXES_TO_MTMRECORD",
  DELETE_INDEX_TO_MTMRECORD:"DELETE_INDEX_TO_MTMRECORD"
}
