const types={
  SET_CATEGORIES:"SET_CATEGORIES",
  SET_CURRENT_CATEGORY_ID:"SET_CURRENT_CATEGORY_ID",
  SET_CURRENT_SONS:"SET_CURRENT_SONS",
  SET_CURRENT_CATEGORY:"SET_CURRENT_CATEGORY",
  SEARCH_CATEGORIES:"SEARCH_CATEGORIES",
  ADD_CATEGORY:"ADD_CATEGORY"

}
export default types