const types={
  SET_CATEGORIES:"SET_CATEGORIES",
  SET_CURRENT_CATEGORY_ID:"SET_CURRENT_CATEGORY_ID",
  SET_CURRENT_SONS:"SET_CURRENT_SONS",
  SET_CURRENT_CATEGORY:"SET_CURRENT_CATEGORY",
  SEARCH_CATEGORIES:"SEARCH_CATEGORIES",
  ADD_CATEGORY:"ADD_CATEGORY",
  ADD_CATEGORY_FIELD:"ADD_CATEGORY_FIELD",
  REMOVE_FIELD:"REMOVE_FIELD",
  ADD_MULTIPLE_FIELD_VALUE:"ADD_MULTIPLE_FIELD_VALUE",
  REMOVE_MULTIPLE_FIELD_VALUE:"REMOVE_MULTIPLE,FIELD_VALUE",
  LOADING_TABLE:"LOADING_TABLE",
  GET_CATEGORY_PRODUCTS:"GET_CATEGORY_PRODUCTS",

}
export default types