const types={
  SET_CATEGORIES:"SET_CATEGORIES",
  SET_CURRENT_CATEGORY_ID:"SET_CURRENT_CATEGORY_ID",
  SET_CURRENT_SONS:"SET_CURRENT_SONS",
  SET_CURRENT_CATEGORY:"SET_CURRENT_CATEGORY",
  SEARCH_CATEGORIES:"SEARCH_CATEGORIES",
  ADD_CATEGORY:"ADD_CATEGORY",
  ADD_CATEGORY_FIELD:"ADD_CATEGORY_FIELD",
  REMOVE_FIELD:"REMOVE_FIELD",
  ADD_MULTIPLE_FIELD_VALUE:"ADD_MULTIPLE_FIELD_VALUE",
  REMOVE_MULTIPLE_FIELD_VALUE:"REMOVE_MULTIPLE,FIELD_VALUE",
  LOADING_TABLE:"LOADING_TABLE",
  SET_CATEGORY_PRODUCTS:"SET_CATEGORY_PRODUCTS",
  GET_TABLES_STATE:"GET_TABLES_STATE",
  SET_TABLES_STATE:"SET_TABLES_STATE",
  SET_TABLE_STATE:"SET_TABLE_STATE"
}
export default types